server:
  port: 8833
  servlet:
    context-path: /api/v1

spring:
  application:
    name: menu-service
  datasource:
    url: "jdbc:mysql://localhost:3306/menu_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: mim123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 600000
    type: redis
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangtanh21102002@gmail.com
    password: udmjflbnfieqzwfw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

storage:
  location: uploads/images

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

